export const fashion = [
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
  {
    url: "",
    detailUrl: "",
    title: {
      shortTitle: "",
      longTitle: "",
    },
    price: {
      mrp: 495,
      cost: 299,
      discount: "39%",
    },
    quantity: 1,
    description: "",
    discount: "Minimum 39% Off",
    tagline: "Grab Now!",
  },
];
